backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blogg"
    label: "Blogginlägg"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publiceringsdatum", name: "date", widget: "datetime" }
      - { label: "Innehåll", name: "body", widget: "markdown" }